### ISSUE TITLE
Migration vom alten Backend

### ISSUE THREAD

**Issue by Kepplinger** [Kepplinger/fit-anmeldesystem-server#1]
Das alte Backend soll .NET Core migriert werden.

**Comment by SakalAndrej** [comment]
@felixhofmann ich werde jetzt einmal das EntityFramework Core einbinden und mich damit beschäftigen damit die Datenbank soweit funktioniert

Wenn ich fertig bin wäre es super wenn du dann die Entity's vom alten Backend ins neue Projekt kopierst!

**Comment by SakalAndrej** [comment]
Erledigt!
