### ISSUE TITLE
Resources Testdaten anlegen

### ISSUE THREAD

**Issue by Kepplinger** [Kepplinger/fit-anmeldesystem-server#34]

**Comment by SakalAndrej** [comment]
im console.filldb erweitern so das ressources als testdaten eingefügt werden @felixhofmann

**Comment by SakalAndrej** [comment]
und branches

**Comment by SakalAndrej** [comment]
erledigt!

**Comment by Kepplinger** [comment]
😘

Sakal Andrej <notifications@github.com> schrieb am Fr., 30. März 2018,
02:34:
