### ISSUE TITLE
Change Protocol übernehmen

### ISSUE THREAD

**Issue by SakalAndrej** [Kepplinger/fit-anmeldesystem-server#36]
Change protocoll um id erweitern

**Comment by felixhofmann** [comment]
dude bennen die issues amoi sprechend

**Comment by SakalAndrej** [comment]
Damits es du a verstehst dude:

Bitte einen Rest endpoint erstellen der es ermöglicht changeprotocoll per id abzulehnen wenn er einer is pending ist!
