### ISSUE TITLE
Event Current nicht korrekt

### ISSUE THREAD

**Issue by Kepplinger** [Kepplinger/fit-anmeldesystem-server#37]
Der GET-Request [http://absleo.htl-leonding.ac.at:8181/api/event/current](http://absleo.htl-leonding.ac.at:8181/api/event/current) liefert in der Response eine Liste von Events zurück, und kein einzelnes Event.

**Comment by felixhofmann** [comment]
wi warads wann dus amoi  mid latest probierst ?

**Comment by felixhofmann** [comment]
eiso  http://absleo.htl-leonding.ac.at:8181/api/event/latest
