### ISSUE TITLE
E-Mail Bausteine

### ISSUE THREAD

**Issue by SakalAndrej** [Kepplinger/fit-anmeldesystem-server#48]
Email Model:

```
        [Required, MaxLength(25)]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Template { get; set; }

        [Required]
        public string Subject { get; set; }
```

E-Mails:

        // isPendingGottenCompany
        // isPendingGottenAdmin
        // IsPendingAcceptedCompany
        // IsPendingDeniedCompany
        // CompanyAssigned
        // SendBookingAcceptedMail
        // SendForgotten

**Comment by Kepplinger** [comment]
Habe den Groß/Klein Fehler korrigiert 😏
